/**
 * model-banner — the generated status-line shim's source.
 *
 * Shared by cli.mjs (writes it on install) and sessionstart.mjs (rewrites it
 * when the plugin root has moved, e.g. after a plugin update) so the two
 * never drift out of sync with each other.
 *
 * Why a shim rather than pointing settings.json straight at the plugin:
 * marketplace-installed plugins live in a directory whose name is a version
 * string that changes on every update. An absolute path into the plugin
 * cache would break on every update. The shim lives at a stable path
 * (~/.claude/model-banner/statusline.mjs) and is re-pointed by the
 * SessionStart hook.
 */

export function shimSource(pluginRoot) {
  return `#!/usr/bin/env node
// Generated by model-banner. Regenerated on session start. Do not edit.
import { pathToFileURL } from "node:url";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const PLUGIN_ROOT = ${JSON.stringify(pluginRoot)};

function readStdin() {
  return new Promise((res) => {
    const chunks = [];
    process.stdin.on("data", (c) => chunks.push(c));
    process.stdin.on("end", () => res(Buffer.concat(chunks).toString("utf8")));
  });
}

function chainFallback(raw) {
  try {
    const cfgPath = join(homedir(), ".claude", "model-banner.json");
    if (!existsSync(cfgPath)) return;
    const cfg = JSON.parse(readFileSync(cfgPath, "utf8"));
    if (!cfg.chain) return;
    const r = spawnSync(cfg.chain, { shell: true, input: raw, encoding: "utf8", timeout: 2000 });
    if (r.status === 0 && r.stdout) process.stdout.write(r.stdout);
  } catch {
    // give up silently — never break the status line
  }
}

const raw = await readStdin();
try {
  const mod = await import(pathToFileURL(join(PLUGIN_ROOT, "statusline", "render.mjs")).href);
  mod.main(raw);
} catch {
  chainFallback(raw);
}
`;
}
